import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {alpinePlant} from '../src/alpine-plants.js';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
async function files(dir){const result=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())result.push(...await files(p));else result.push(p);}return result;}
const assets=[],oldRoot='release/Seceda-Windows-v0.7/resources/app';
for(const file of await files('assets')){const b=await fs.readFile(file);let original=false;try{const old=await fs.readFile(path.join(oldRoot,file));assert.equal(hash(b),hash(old),`Changed old asset: ${file}`);original=true;}catch(e){if(e.code!=='ENOENT')throw e;}assets.push({file,bytes:b.length,sha256:hash(b),originalV07:original});}
const geometry=Array.from({length:5},(_,t)=>({type:['Yellow composite','Pink clover','White daisy','Violet bell','Fallback broad leaves'][t],levels:[false,true].map(low=>{const g=alpinePlant(t,low,0,t===0);return{triangles:g.index.count/3,vertices:g.attributes.position.count,bytes:Object.values(g.attributes).reduce((n,a)=>n+a.array.byteLength,0)+g.index.array.byteLength};})}));
const report={allExistingV07AssetsByteIdentical:true,totalAssetBytes:assets.reduce((n,a)=>n+a.bytes,0),newAssetBytes:assets.filter(a=>!a.originalV07).reduce((n,a)=>n+a.bytes,0),newAssetLicense:'No new third-party asset files. Original code-generated land-cover map, conifer crowns, sward and pasture fragments.',newTextureSizes:'Runtime 1200x1000 RGBA land-cover data with mipmaps, 361x381 R32F middle-sward height map. Existing licensed image sizes unchanged.',geometry,optimizedRosettes:JSON.parse(await fs.readFile('assets/models/dandelion_01/optimization.json')),turf:{nearBladesPerSquareMetre:240,nearBladesPerTile:15360,nearTrianglesPerTile:46080,midTrianglesPerTile:1280,tileMetres:8,nearFade:[22,33],midFade:[58,90],originalTexture:[1024,1024],heightTexture:[721,521]},rock:{diffuse:[4096,4096],height:[2048,2048],repeatMetres:[20,80],resolutionsUnchanged:true},assets};
await fs.writeFile('artifacts/landscape-v08/assets.json',JSON.stringify(report,null,2));console.log(JSON.stringify({...report,assets:undefined},null,2));
