import {createRequire} from 'node:module';import fs from 'node:fs/promises';
const {_electron}=createRequire(import.meta.url)('C:/Users/chris/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const app=await _electron.launch({executablePath:'node_modules/electron/dist/electron.exe',args:['.']});
try {const p=await app.firstWindow();p.on('console',m=>{if(m.type()==='error')console.log(m.text())});await p.waitForFunction(()=>window.__seceda?.ready,null,{timeout:120000});await p.setViewportSize({width:1600,height:1000});
 await p.evaluate(()=>{const q=window.__seceda;q.hideUI();q.camera.fov=38;q.camera.updateProjectionMatrix();q.setPose(150,-120,-1.12,-.27);});await p.waitForTimeout(1000);
 const info=await p.evaluate(async()=>{const T=await import('three'),q=window.__seceda,r=new T.Raycaster(),out=[];for(const [x,y]of [[1040,330],[1040,500],[1080,530],[1520,90],[660,55],[1200,390]]){r.setFromCamera(new T.Vector2(x/800-1,1-y/500),q.camera);const hits=r.intersectObjects(q.scene.children,false).filter(i=>i.object.isMesh&&!i.object.isInstancedMesh&&i.object.geometry.attributes.position.count>500);out.push({pixel:[x,y],hits:hits.slice(0,3).map(h=>({name:h.object.name,position:h.point.toArray(),triangle:h.faceIndex,normal:h.face.normal.toArray(),material:Array.isArray(h.object.material)?h.object.material[h.face.materialIndex].customProgramCacheKey():h.object.material.customProgramCacheKey()}))});}return out;});
 await fs.writeFile('artifacts/ledge-v011/surface-diagnosis.json',JSON.stringify(info,null,2));console.log(JSON.stringify(info,null,2));
 await p.evaluate(async()=>{const T=await import('three'),q=window.__seceda;let i=0;for(const m of q.scene.children){if(!m.isMesh||m.isInstancedMesh||m.geometry.attributes.position?.count<10000)continue;const colors=[0x444444,0x666666,0x888888,0xff0000,0x00ffff,0x0000ff,0xffff00];const mat=new T.MeshBasicMaterial({color:colors[i++],side:T.DoubleSide});m.material=Array.isArray(m.material)?[mat,mat]:mat;}});await p.waitForTimeout(300);await p.screenshot({path:'artifacts/ledge-v011/surface-ids.png'});
}finally{await app.close()}
