import {addGroundOutcrops} from './ground-outcrops.js';
import {addRegionalShrubs} from './regional-shrubs.js';
import {addRegionalDebris} from './regional-debris.js';
import {SurveyTiles} from './survey-tiles.js';
import {addTiledTerrain} from './tiled-terrain.js';
import {prepareMeadowHabitat} from './meadow-habitat.js';
import {explorationInfo} from './exploration.js';
import {prepareLedgeCoordinates,sculptLedge,sculptLedgeSupport} from './ledge-study.js';
import {addLandmarks} from './landmarks.js';
import {refineCliff,addCliffDebris} from './cliff-surface.js';
import {addPastureSward} from './pasture-sward.js';
import {prepareLandCover,addValleyWoodland} from './land-cover.js';
import {addTurf} from './turf.js';
import {bakeMassifLight} from './massif-light.js';
import {addRidgeBenches} from './ridge-benches.js';
import {addSummitFins} from './summit-fins.js';
import {addRidgeWalls} from './ridge-walls.js';
import {addRidge} from './ridge.js';
import {addEmbeddedStones} from './trail-details.js';
import {addMeadow} from './ridge-meadow.js';
import {makeAtmosphere} from './atmosphere.js';
import * as THREE from 'three';
import{Terrain,createRoute,routeDistance}from'./terrain.js';import{groundMaterial,prepareMaterials}from'./materials.js';import{addTrail,addRocks,addMarkers}from'./details.js';import{Walker}from'./player.js';import{prepareLandscape,SUN_DIRECTION}from'./landscape.js';import{Ambience}from'./audio.js';
const $=id=>document.getElementById(id);const canvas=$('world');
try{
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.94;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0xa1b7c8,.000075);const camera=new THREE.PerspectiveCamera(66,innerWidth/innerHeight,.08,22000);camera.rotation.order='YXZ';scene.userData.version='0.15.0';const sky=makeAtmosphere(renderer);scene.add(sky);
const hemi=new THREE.HemisphereLight(0xcbdcee,0x8a8975,1.08);scene.add(hemi);const sun=new THREE.DirectionalLight(0xfff5e5,2.85);sun.position.copy(SUN_DIRECTION).multiplyScalar(1800);sun.castShadow=true;sun.shadow.mapSize.set(4096,4096);sun.shadow.camera.near=1;sun.shadow.camera.far=5000;sun.shadow.camera.left=-180;sun.shadow.camera.right=180;sun.shadow.camera.top=180;sun.shadow.camera.bottom=-180;sun.shadow.bias=-.000035;sun.shadow.normalBias=.06;sun.target.position.set(70,-5,30);sun.position.add(sun.target.position);scene.add(sun,sun.target);
await prepareMaterials();const terrain=await new Terrain().load();$('loadText').textContent='Growing the high meadow…';await new Promise(r=>setTimeout(r,20));const route=createRoute(terrain);$('loadText').textContent='Reading the regional survey';const visualTerrain=await new SurveyTiles(terrain).load();camera.position.copy(route.points[0]).add(new THREE.Vector3(0,1.72,0));camera.rotation.set(.025,-.65,0,'YXZ');await prepareLandscape(visualTerrain,route);scene.userData.meadowHabitat=prepareMeadowHabitat(terrain);scene.userData.landCover=await prepareLandCover(visualTerrain);const mat=groundMaterial(false,false,false,false,true);const survey=await addTiledTerrain(scene,visualTerrain,mat,camera);scene.userData.surveyChunks=survey.info;scene.userData.exploration=explorationInfo;
addTrail(scene,terrain,route);addEmbeddedStones(scene,terrain,route);const grass=await addMeadow(scene,terrain,route);const colliders=addRocks(scene,terrain,route);colliders.push(...await addLandmarks(scene,terrain,route));const cliffs=refineCliff(addRidge(scene,terrain),1);refineCliff(addSummitFins(scene,terrain),3);const walls=refineCliff(addRidgeWalls(scene,terrain),2);sculptLedge(refineCliff(prepareLedgeCoordinates(addRidgeBenches(scene,terrain)),4,false));sculptLedgeSupport(walls);const regionalRock={tiles:[],info:{method:"Small scenic limestone relief integrated into native survey tiles; original principal ridge pinned",oldV13OverlayRetired:true}};scene.userData.regionalRock=regionalRock.info;bakeMassifLight(renderer,scene,3072);await addCliffDebris(scene);const turf=addTurf(scene,terrain);const woodland=addValleyWoodland(scene,visualTerrain);colliders.push(...woodland.colliders);const regionalDebris=await addRegionalDebris(scene,visualTerrain);await addRegionalShrubs(scene,visualTerrain);await addGroundOutcrops(scene,visualTerrain);const sward=addPastureSward(scene,visualTerrain);scene.userData.sward=sward.info;
const player=new Walker(terrain,colliders,route.points[0]);const audio=new Ambience();const keys=new Set();let started=false,active=false,reached=false,elapsed=0,toastUntil=0;let motion=false,sensitivity=1;let frameTimes=[],previous=performance.now();
function pose(){camera.position.copy(player.position);if(motion&&active)camera.position.y+=Math.sin(player.distance*8)*.016*Math.min(1,player.velocity.length());camera.rotation.y=player.yaw;camera.rotation.x=player.pitch;sky.position.copy(camera.position);}
function toast(t){$('toast').textContent=t;toastUntil=elapsed+2.5;}
function clearArrival(){reached=false;$('arrival').classList.add('hidden');}
function resetWalk(){player.reset();clearArrival();keys.clear();$('toast').textContent='';toastUntil=0;pose();updateHUD();}
async function enter(){started=true;audio.start();try{await canvas.requestPointerLock();}catch{toast('Click the landscape to capture the mouse.');}if(document.pointerLockElement===canvas){active=true;$('intro').classList.add('hidden');$('pause').classList.add('hidden');$('reticle').classList.remove('hidden');}}
$('enter').onclick=enter;$('resume').onclick=enter;canvas.onclick=()=>{if(!active)enter();};document.addEventListener('pointerlockchange',()=>{active=document.pointerLockElement===canvas;keys.clear();player.velocity.set(0,0);$('intro').classList.toggle('hidden',started);$('pause').classList.toggle('hidden',active||!started);$('reticle').classList.toggle('hidden',!active);if(active)audio.start();else audio.pause();});document.addEventListener('mousemove',e=>{if(active){player.yaw-=e.movementX*.0018*sensitivity;player.pitch=THREE.MathUtils.clamp(player.pitch-e.movementY*.0018*sensitivity,-1.42,1.42);}});
document.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&document.pointerLockElement){document.exitPointerLock();}if(e.code==='KeyH'&&!e.repeat)document.body.classList.toggle('clean');if(e.code==='KeyR'&&!e.repeat){resetWalk();toast('Back at the trailhead');}if(active)keys.add(e.code);});document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();player.velocity.set(0,0);if(document.pointerLockElement)document.exitPointerLock();});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();audio.pause();}});
$('sensitivity').oninput=e=>sensitivity=Number(e.target.value);$('motion').onchange=e=>motion=e.target.checked;$('sound').onchange=e=>audio.setEnabled(e.target.checked);$('quality').onchange=e=>{renderer.setPixelRatio(e.target.value==='high'?Math.min(devicePixelRatio,1.5):1);grass.setQuality(e.target.value==='high');renderer.shadowMap.enabled=e.target.value==='high';};
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
function updateHUD(){const r=routeDistance(route,player.position.x,player.position.z),end=route.points.at(-1),remaining=Math.round((1-r.index/(route.points.length-1))*route.length);if(!reached&&Math.hypot(player.position.x-end.x,player.position.z-end.z)<6){reached=true;$('arrival').classList.remove('hidden');} $('objective').textContent=reached?'SECEDA / THE ODLE':'THE RIDGE VIEWPOINT';$('distance').textContent=reached?'Look east along the pale rock towers':`${remaining} m along the trail`;$('altitude').textContent=`${Math.round(player.position.y-1.72+2500).toLocaleString('en')} m`;const heading=(((-player.yaw*180/Math.PI)%360)+360)%360;const names=['N','NE','E','SE','S','SW','W','NW'];$('bearing').textContent=names[Math.round(heading/45)%8];}
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-previous)/1000,.1);frameTimes.push(now-previous);if(frameTimes.length>180)frameTimes.shift();previous=now;elapsed+=dt;if(active){let left=dt;while(left>0){const s=Math.min(left,1/60);const result=player.step(s,keys);if(result.blocked)toast('Steep ground or the edge of the open pasture — turn back toward the meadow.');left-=s;}audio.update(player.distance,elapsed);}if(camera.position.distanceToSquared(sun.target.position)>24000){sun.target.position.set(camera.position.x, camera.position.y-1.72,camera.position.z);sun.position.copy(sun.target.position).addScaledVector(SUN_DIRECTION,1800);renderer.shadowMap.needsUpdate=true;}survey.update(camera);turf.update(elapsed,camera);sward.update(camera);if(grass.update(elapsed,camera))renderer.shadowMap.needsUpdate=true;if(elapsed>toastUntil)$('toast').textContent='';pose();updateHUD();renderer.render(scene,camera);renderer.shadowMap.autoUpdate=false;}
pose();renderer.compile(scene,camera);$('loading').classList.add('hidden');$('intro').classList.remove('hidden');requestAnimationFrame(frame);
// Deliberate QA surface: all simulated walking goes through the production controller.
window.__seceda={ready:true,regionalDebris,visualTerrain,regionalRock,survey,turf,grass,woodland,terrain,route,player,scene,camera,renderer,colliders,cliffs,pose,stats:()=>({position:player.position.toArray(),reached,active,routeMetres:route.length,triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls,meanFrameMs:frameTimes.reduce((a,b)=>a+b,0)/frameTimes.length}),setPose(x,z,yaw,pitch=.02){clearArrival();player.position.set(x,terrain.height(x,z)+1.72,z);player.velocity.set(0,0);player.yaw=yaw;player.pitch=pitch;pose();},walk(seconds,codes=['KeyW']){for(let t=0;t<seconds;t+=1/60)player.step(1/60,new Set(codes));pose();updateHUD();return this.stats();},hideUI(){document.body.classList.add('clean');$('intro').classList.add('hidden');$('pause').classList.add('hidden');},showUI(){document.body.classList.remove('clean');},reset(){resetWalk();},routeReport(){return route.points.map(p=>({x:p.x,z:p.z,y:p.y,slope:terrain.slope(p.x,p.z)}));}};
}catch(e){console.error(e);$('loadText').textContent='The scene could not start. '+e.message;}
